{% set version = "1.3.8" %}
{% set name = "libxmlsec1" %}

package:
  name: libxmlsec1
  version: {{ version }}

source:
  url: https://github.com/lsh123/xmlsec/releases/download/{{ version }}/xmlsec1-{{ version }}.tar.gz
  sha256: d0180916ae71be28415a6fa919a0684433ec9ec3ba1cc0866910b02e5e13f5bd

build:
  number: 0
  run_exports:
    # compatibility is not tracked at abi-laboratory, assume same as libxml2
    - {{ pin_subpackage('libxmlsec1', max_pin='x.x') }}
  skip: true  # [win]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - make
    - libtool
  host:
    # GCRYPT_MIN_VERSION=1.4.0
    - libgcrypt 1.11.2
    - libgpg-error 1.51
    - libtool 2.4.7
    # LIBXML2_MIN_VERSION=2.8.0
    - libxml2 {{ libxml2 }}
    # LIBXSLT_MIN_VERSION=1.0.20
    - libxslt {{ libxslt }}
    - openssl {{ openssl }}
  run:
    - {{ pin_compatible('libtool') }}

test:
  requires:
    - ripgrep
  commands:
    - xmlsec1 --help
    - xmlsec1 --version | rg {{ version }}

about:
  home: https://www.aleksey.com/xmlsec
  license: MIT
  license_family: MIT
  license_file: Copyright
  summary: XML Security Library
  description: |
    XML Security Library is a C library based on LibXML2.
    The library supports major XML security standards.
  dev_url: https://github.com/lsh123/xmlsec
  doc_url: https://www.aleksey.com/xmlsec/documentation.html

extra:
  skip-lints:  # due to the libtool issue explained above
    - build_tools_must_be_in_build
